spring.application.name=zerojuice

# 3. DB 드라이버 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. JPA/Hibernate 설정 (콘솔에서 SQL 문을 확인하기 위함)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

spring.data.redis.host=13.209.9.201
spring.data.redis.port=8379
spring.data.redis.password=zerostress!!